#!/usr/bin/env bash
selected=$(find ~/projects -mindepth 1 -maxdepth 1 -type d | fzf)
[ -z "$selected" ] && exit 0
session_name=$(basename "$selected" | tr . _)
if ! tmux has-session -t "$session_name" 2>/dev/null; then
  tmux new-session -ds "$session_name" -c "$selected"
fi
tmux switch-client -t "$session_name" 2>/dev/null || tmux attach -t "$session_name"
